In [130]:
!pip show sklearn -v

Name: sklearn
Version: 0.0
Summary: A set of python modules for machine learning and data mining
Home-page: https://pypi.python.org/pypi/scikit-learn/
Author: UNKNOWN
Author-email: UNKNOWN
License: None
Location: /usr/local/lib/python3.7/dist-packages
Requires: scikit-learn
Required-by: 
Metadata-Version: 2.1
Installer: pip
Classifiers:
Entry-points:


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
spc_dataset = pd.read_csv('/content/dataset_spc_kaggle.csv',delimiter=',')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (9) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [ ]:
spc_dataset.head(5)

customer_id  ... transactions_kaggle_raw_data_id
0  0715dc59-cf23-401a-97c5-24e9aed7384a  ...                             NaN
1  0715dc59-cf23-401a-97c5-24e9aed7384a  ...                             NaN
2  d5e88b46-22fd-4e51-ba5f-41d2fe0f3500  ...                             NaN
3  d5e88b46-22fd-4e51-ba5f-41d2fe0f3500  ...                             NaN
4  49b70cc1-464f-4684-928b-83a033c2385b  ...                             NaN

[5 rows x 24 columns]

In [ ]:
spc_dataset.shape

(52471, 24)

In [ ]:
spc_dataset['transactions_category'].unique()

array([nan, 'Outros Serviços', 'Restaurantes', 'Supermercados',
       'Farmácias', 'Varejo', 'Compras Online', 'Lojas de Departamento',
       'Agências de Turismo', 'Vestuário', 'Postos de Combustíveis',
       'Hotéis', 'Artigos Eletrônicos', 'Hospitais de Clínicas',
       'Companhias Aéreas', 'Móveis e Decoração',
       'Materiais de Construção', 'Não Especificado', 'Auto Peças',
       'Joalherias', 'Transações Financeiras', 'Aluguéis de Carros'],
      dtype=object)

In [ ]:
df_cid = spc_dataset[['customer_products_id','customer_id','customer_state', 'customer_city', 'customer_age', 'customer_avg_income','customer_products_active','product_id','transactions_total_limit','transactions_category']]
df_spc =  spc_dataset[['customer_state', 'customer_city', 'customer_age', 'customer_avg_income','customer_products_active','product_id','transactions_total_limit','transactions_category']]
df_spc.head()

customer_state  ... transactions_category
0             CE  ...                   NaN
1             CE  ...                   NaN
2             SC  ...                   NaN
3             SC  ...                   NaN
4             PI  ...                   NaN

[5 rows x 8 columns]

In [ ]:
df_spc['customer_age'] = df_spc['customer_age'].fillna(df_spc['customer_age'].mean())

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
df_spc['customer_avg_income'] = df_spc['customer_avg_income'].fillna(df_spc['customer_avg_income'].mean())

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
df_spc['customer_products_active'] = df_spc['customer_products_active'].fillna(False)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
df_spc['transactions_category'] = df_spc['transactions_category'].fillna('Não Especificado')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
df_spc['transactions_total_limit'] = df_spc['transactions_total_limit'].fillna(df_spc['transactions_total_limit'].mean())

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
df_spc = df_spc.dropna(subset=['customer_state','customer_city','product_id'])
df_cid = df_cid.dropna(subset=['customer_state','customer_city','product_id'])
df_spc.shape

(47989, 8)

In [ ]:
df_cid.shape

(47989, 10)

In [ ]:
df_spc.head()

customer_state  ... transactions_category
0             CE  ...      Não Especificado
1             CE  ...      Não Especificado
2             SC  ...      Não Especificado
3             SC  ...      Não Especificado
4             PI  ...      Não Especificado

[5 rows x 8 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

In [ ]:
state_encoder = LabelEncoder()
state_encoder.fit(df_spc['customer_state'].unique())
df_spc['customer_state'] = state_encoder.transform(df_spc['customer_state'])
df_spc['customer_state'].unique()

array([ 5, 23, 16,  9, 10,  4, 15, 22, 13, 25,  8, 18, 17, 12, 26,  2,  6,
        7, 11, 20,  1,  0, 21, 24, 19,  3, 14])

In [ ]:
city_encoder = LabelEncoder()
city_encoder.fit(df_spc['customer_city'].unique())
df_spc['customer_city'] = city_encoder.transform(df_spc['customer_city'])
df_spc['customer_city'].unique()

array([ 957,  154, 1930, ..., 1109, 1691,  956])

In [ ]:
product_encoder = LabelEncoder()
product_encoder.fit(df_spc['product_id'].unique())
df_spc['product_id'] = product_encoder.transform(df_spc['product_id'])
df_spc['product_id'].unique()

array([ 2,  3,  0,  4,  9,  7,  5, 12, 13,  6, 10, 16, 15,  1, 18, 14, 17,
       11,  8])

In [ ]:
category_encoder = LabelEncoder()
category_encoder.fit(df_spc['transactions_category'].unique())
df_spc['transactions_category'] = category_encoder.transform(df_spc['transactions_category'])
df_spc['transactions_category'].unique()

array([13, 14, 16, 17,  6, 19,  5, 10,  0, 20, 15,  8,  2,  7,  4, 12, 11,
        3,  9, 18,  1])

In [ ]:
df_spc.head()
df_spc.columns

Index(['customer_state', 'customer_city', 'customer_age',
       'customer_avg_income', 'customer_products_active', 'product_id',
       'transactions_total_limit', 'transactions_category'],
      dtype='object')

In [ ]:
scaler = MinMaxScaler()
X = df_spc.drop(columns=['product_id'])
X = scaler.fit_transform(X)
X.shape

(47989, 7)

In [ ]:
Y = np.array(df_spc['product_id'])
Y

array([ 2,  3,  0, ...,  6,  3, 15])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)


In [ ]:
x_train.shape

(32152, 7)

In [ ]:
x_test.shape

(15837, 7)

In [ ]:
y_test.shape

(15837,)

In [ ]:
np.unique(y_test)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [ ]:
from sklearn.cluster import KMeans

In [ ]:
kmeans = KMeans(n_clusters=19, random_state=0)
yk_train = kmeans.fit_predict(x_train)
yk_test = kmeans.predict(x_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
model = KNeighborsClassifier(n_neighbors=20)
model.fit(x_train,yk_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=20, p=2,
                     weights='uniform')

In [ ]:
model.score(x_test, yk_test)

0.9863610532297784

In [ ]:
test = model.predict(x_test)
test

array([18, 12,  2, ..., 11,  5, 12], dtype=int32)

In [ ]:
product_encoder.inverse_transform(model.predict(x_test))

array(['fedb8579-39bf-4f3e-a83d-733967e3426e',
       'b015f0c8-fa88-4f71-aa59-abe6c311ee5e',
       '25930731-2fb1-493a-8d18-4347fbafd1a9', ...,
       'a362a90f-1f3e-48fa-b6a6-caf248ad0b4d',
       '61ce7fa6-ba83-47ae-b7bd-71dceccc3780',
       'b015f0c8-fa88-4f71-aa59-abe6c311ee5e'], dtype=object)

In [ ]:
model.predict_proba([x_test[0]])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1.]])

In [ ]:
model.predict([x_test[0]])

array([18], dtype=int32)

In [ ]:
!pip install joblib

In [ ]:
from joblib import dump

In [ ]:
dump(model,'model.dump')

['model.dump']

In [ ]:
X.shape

(47989, 7)

In [ ]:
pd.Series(product_encoder.inverse_transform(model.predict(X)))

0        f5531785-1f3f-416d-90be-05ea17b6fa20
1        f5531785-1f3f-416d-90be-05ea17b6fa20
2        da8dceab-4690-45ca-81e5-9dbbc7469609
3        bdf8ccbb-62ab-4d59-980c-301b49444c1b
4        2291cccc-64fb-4a20-9895-20f33219571e
                         ...                 
47984    da8dceab-4690-45ca-81e5-9dbbc7469609
47985    bdf8ccbb-62ab-4d59-980c-301b49444c1b
47986    da8dceab-4690-45ca-81e5-9dbbc7469609
47987    bdf8ccbb-62ab-4d59-980c-301b49444c1b
47988    2291cccc-64fb-4a20-9895-20f33219571e
Length: 47989, dtype: object

In [ ]:
df_cid.head(2)

customer_products_id  ... transactions_category
0  6637a55c-2c26-4131-b31d-dc6d89c5c32e  ...                   NaN
1  5ee5db2b-a88f-44ba-b562-f35aa79635f0  ...                   NaN

[2 rows x 10 columns]

In [ ]:

df_cid = df_cid.drop_duplicates(subset=['customer_products_id'])
df_cid['customer_products_id'].count()

25405

In [ ]:
df_cid[['customer_products_id','product_id']].to_csv('de_para.csv')

In [ ]:
def encode_transform(data):
    customer_state = data["customer_state"]
    customer_city = data["customer_city"]
    customer_age = data["customer_age"]
    customer_avg_income = data["customer_avg_income"]
    customer_products_active = data["customer_products_active"]
    transactions_total_limit = data["transactions_total_limit"]
    transactions_category = data["transactions_category"]
    customer_state, = state_encoder.transform([customer_state])
    customer_city, = city_encoder.transform([customer_city])
    transactions_category, = category_encoder.transform([transactions_category])
    scaled_data, = scaler.transform([[
                                     customer_state,
                                     customer_city,
                                     customer_age,
                                     customer_avg_income,
                                     customer_products_active,
                                     transactions_total_limit,
                                     transactions_category
                                    ]])
    return scaled_data

def untransform_product(product):
  product_id, = product_encoder.inverse_transform([product])
  return product_id

In [ ]:
encode_transform({
    "customer_state":"CE",
    "customer_city": "Jaguaruana",
    "customer_age": 40.0,
    "customer_avg_income": 3594,
    "customer_products_active": True,
    "transactions_total_limit": 7626.014464,
    "transactions_category": "Não Especificado"
})

array([0.19230769, 0.46209561, 0.20588235, 0.0951509 , 1.        ,
       0.18453437, 0.65      ])

In [ ]:
untransform_product(1)

'2291cccc-64fb-4a20-9895-20f33219571e'

In [ ]:
untransform_product(model.predict([x_test[0]])[0])

'fedb8579-39bf-4f3e-a83d-733967e3426e'

In [ ]:
dump(product_encoder,'product_encoder.dump')
dump(state_encoder,'state_encoder')
dump(city_encoder,'city_encoder')
dump(category_encoder,'category_encoder')
dump(scaler,'scaler.dump')

['scaler.dump']